USE [master]
GO

/****** Object:  Database [CoreStoreDatabase]    Script Date: 22/05/2020 23:20:58 ******/
CREATE DATABASE [CoreStoreDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoreStoreDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CoreStoreDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoreStoreDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CoreStoreDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoreStoreDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoreStoreDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoreStoreDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoreStoreDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoreStoreDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoreStoreDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [CoreStoreDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [CoreStoreDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoreStoreDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoreStoreDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoreStoreDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoreStoreDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoreStoreDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CoreStoreDatabase] SET  READ_WRITE 
GO


